/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

var main_exports = {};
__export(main_exports, {
  default: () => Paper2SlidesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
var DEFAULT_SETTINGS = {
  pythonPath: "python3",
  p2sPath: "",
  outputType: "slides",
  style: "doraemon",
  customStyle: "",
  fastMode: false
};
var Paper2SlidesPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new Paper2SlidesSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && this.isSupportedSource(file)) {
          menu.addItem((item) => {
            item.setTitle("Generate Slides/Poster (Paper2Slides)").setIcon("presentation").onClick(async () => {
              await this.generateSlides(file);
            });
          });
        }
      })
    );
    this.addCommand({
      id: "generate-slides-current-file",
      name: "Generate Slides/Poster from current file",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && this.isSupportedSource(file)) {
          if (!checking) {
            void this.generateSlides(file);
          }
          return true;
        }
        return false;
      }
    });
  }
  isSupportedSource(file) {
    return file.extension === "pdf" || file.extension === "md";
  }
  getContentType(file) {
    return file.extension === "md" ? "general" : "paper";
  }
  getStyleArgument() {
    if (this.settings.style === "custom") {
      const prompt = this.settings.customStyle.trim();
      return prompt.length > 0 ? prompt : "minimal clean academic presentation";
    }
    return this.settings.style;
  }
  getConfigDirName() {
    const style = this.settings.style === "custom" ? `custom_${this.settings.customStyle.trim().slice(0, 16).replace(/ /g, "_").replace(/\//g, "_") || "custom"}` : this.settings.style;
    const detail = this.settings.outputType === "poster" ? "medium" : "short";
    return `${this.settings.outputType}_${style}_${detail}`;
  }
  async ensureVaultFolder(folderPath) {
    if (folderPath === "." || folderPath === "" || await this.app.vault.adapter.exists(folderPath)) {
      return;
    }
    const parent = path.posix.dirname(folderPath);
    if (parent !== folderPath) {
      await this.ensureVaultFolder(parent);
    }
    await this.app.vault.createFolder(folderPath);
  }
  async generateSlides(file) {
    const repoPath = this.settings.p2sPath.trim();
    if (!repoPath) {
      new import_obsidian.Notice("Set the Paper2Slides repo path in the plugin settings first.");
      return;
    }
    if (!fs.existsSync(repoPath)) {
      new import_obsidian.Notice("The configured Paper2Slides repo path does not exist.");
      return;
    }
    if (!fs.existsSync(path.join(repoPath, "paper2slides"))) {
      new import_obsidian.Notice("The repo path looks wrong. Expected a folder containing the paper2slides package.");
      return;
    }
    const adapter = this.app.vault.adapter;
    if (!(adapter instanceof import_obsidian.FileSystemAdapter)) {
      new import_obsidian.Notice("Only local vaults are supported right now.");
      return;
    }
    const fullInputPath = path.join(adapter.getBasePath(), file.path);
    const contentType = this.getContentType(file);
    const styleArg = this.getStyleArgument();
    new import_obsidian.Notice(`Starting Paper2Slides for ${file.name}...`);
    const args = [
      "-m",
      "paper2slides",
      "--input",
      fullInputPath,
      "--content",
      contentType,
      "--output",
      this.settings.outputType,
      "--style",
      styleArg
    ];
    if (this.settings.fastMode) {
      args.push("--fast");
    }
    console.log(`Running: ${this.settings.pythonPath} ${args.join(" ")}`);
    const p2sProcess = (0, import_child_process.spawn)(this.settings.pythonPath, args, {
      cwd: repoPath,
      env: { ...process.env }
    });
    p2sProcess.on("error", (error) => {
      console.error("Paper2Slides process error:", error);
      new import_obsidian.Notice(`Could not start ${this.settings.pythonPath}. Check the Python command in settings.`);
    });
    p2sProcess.stdout.on("data", (data) => {
      const output = data.toString();
      console.log(`Paper2Slides stdout: ${output}`);
      const lines = output.split("\n");
      for (const line of lines) {
        if (line.includes("Starting Stage:")) {
          new import_obsidian.Notice(`Paper2Slides: ${line.trim()}`);
        }
      }
    });
    p2sProcess.stderr.on("data", (data) => {
      console.error(`Paper2Slides stderr: ${data}`);
    });
    p2sProcess.on("close", async (code) => {
      if (code === 0) {
        new import_obsidian.Notice("Paper2Slides finished. Importing the newest result into the vault...");
        await this.importLatestOutputs(file, contentType);
      } else {
        new import_obsidian.Notice(`Paper2Slides failed with exit code ${code}. Open the developer console for logs.`);
      }
    });
  }
  collectGeneratedFiles(dir) {
    if (!fs.existsSync(dir)) {
      return [];
    }
    const collected = [];
    for (const name of fs.readdirSync(dir)) {
      const currentPath = path.join(dir, name);
      const stat = fs.statSync(currentPath);
      if (stat.isDirectory()) {
        collected.push(...this.collectGeneratedFiles(currentPath));
        continue;
      }
      if (name.endsWith(".pdf") || name.endsWith(".png") || name.endsWith(".md")) {
        collected.push(currentPath);
      }
    }
    return collected;
  }
  getLatestTimestampDir(configDir) {
    var _a;
    if (!fs.existsSync(configDir)) {
      return null;
    }
    const candidates = fs.readdirSync(configDir).map((name) => path.join(configDir, name)).filter((candidate) => fs.statSync(candidate).isDirectory()).sort((a, b) => path.basename(b).localeCompare(path.basename(a)));
    return (_a = candidates[0]) != null ? _a : null;
  }
  async writeVaultFile(vaultPath, sourcePath) {
    const data = fs.readFileSync(sourcePath);
    if (sourcePath.endsWith(".md")) {
      const content = data.toString("utf8");
      if (await this.app.vault.adapter.exists(vaultPath)) {
        await this.app.vault.adapter.write(vaultPath, content);
      } else {
        await this.app.vault.create(vaultPath, content);
      }
      return;
    }
    const binary = data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength);
    if (await this.app.vault.adapter.exists(vaultPath)) {
      await this.app.vault.adapter.writeBinary(vaultPath, binary);
    } else {
      await this.app.vault.createBinary(vaultPath, binary);
    }
  }
  async importLatestOutputs(sourceFile, contentType) {
    const projectDir = path.join(this.settings.p2sPath, "outputs", sourceFile.basename, contentType);
    const modeDir = path.join(projectDir, this.settings.fastMode ? "fast" : "normal");
    const configDir = path.join(modeDir, this.getConfigDirName());
    const latestRunDir = this.getLatestTimestampDir(configDir);
    const summaryPath = path.join(modeDir, "summary.md");
    const sourcePaths = /* @__PURE__ */ new Set();
    if (fs.existsSync(summaryPath)) {
      sourcePaths.add(summaryPath);
    }
    if (latestRunDir) {
      for (const filePath of this.collectGeneratedFiles(latestRunDir)) {
        sourcePaths.add(filePath);
      }
    }
    if (sourcePaths.size === 0) {
      new import_obsidian.Notice("Paper2Slides finished, but no output files were found to import.");
      return;
    }
    const targetDir = path.posix.join("Paper2Slides", sourceFile.basename);
    await this.ensureVaultFolder(targetDir);
    let importedCount = 0;
    for (const sourcePath of sourcePaths) {
      const fileName = path.basename(sourcePath);
      const vaultPath = path.posix.join(targetDir, fileName);
      await this.writeVaultFile(vaultPath, sourcePath);
      importedCount += 1;
    }
    new import_obsidian.Notice(`Imported ${importedCount} files into ${targetDir}`);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var Paper2SlidesSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Paper2Slides settings" });
    new import_obsidian.Setting(containerEl).setName("Python command").setDesc("Usually python3. Point this to your venv only if you really need to.").addText((text) => text.setPlaceholder("python3").setValue(this.plugin.settings.pythonPath).onChange(async (value) => {
      this.plugin.settings.pythonPath = value.trim() || "python3";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Paper2Slides repo path").setDesc("Absolute path to your cloned Paper2Slides checkout.").addText((text) => text.setPlaceholder("/path/to/Paper2Slides").setValue(this.plugin.settings.p2sPath).onChange(async (value) => {
      this.plugin.settings.p2sPath = value.trim();
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Generation" });
    new import_obsidian.Setting(containerEl).setName("Output type").setDesc("Generate either slides or a poster.").addDropdown((dropdown) => dropdown.addOption("slides", "Slides").addOption("poster", "Poster").setValue(this.plugin.settings.outputType).onChange(async (value) => {
      this.plugin.settings.outputType = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Style preset").setDesc("Use one of the built-in styles, or switch to custom and type your own prompt below.").addDropdown((dropdown) => dropdown.addOption("academic", "Academic").addOption("doraemon", "Doraemon").addOption("custom", "Custom").setValue(this.plugin.settings.style).onChange(async (value) => {
      this.plugin.settings.style = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.style === "custom") {
      new import_obsidian.Setting(containerEl).setName("Custom style prompt").setDesc("Passed straight through to Paper2Slides as the style argument.").addTextArea((text) => text.setPlaceholder("Clean editorial slides with warm neutrals and subtle diagrams.").setValue(this.plugin.settings.customStyle).onChange(async (value) => {
        this.plugin.settings.customStyle = value;
        await this.plugin.saveSettings();
      }));
    }
    new import_obsidian.Setting(containerEl).setName("Fast mode").setDesc("Skip RAG indexing. Good for quick passes and smaller inputs.").addToggle((toggle) => toggle.setValue(this.plugin.settings.fastMode).onChange(async (value) => {
      this.plugin.settings.fastMode = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("p", {
      text: "PDF files run as paper mode. Markdown notes run as general mode automatically."
    });
  }
};
